<a href="https://colab.research.google.com/github/CodeHombre/Deep-Learning-Projects/blob/main/MNIST_DNN_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

TypeError: ignored

In [ ]:
import io
data_train = pd.read_csv(io.BytesIO(uploaded['mnist_train.csv']))
data_test = pd.read_csv(io.BytesIO(uploaded['mnist_test.csv']))

data_train = np.array(data_train).T
data_test = np.array(data_test).T

Y_train = data_train[0]
X_train = data_train[1:]

Y_test = data_test[0]
X_test = data_test[1:]

print(Y_train)
print(X_train)
print(Y_test)
print(X_test)

[0 4 1 ... 5 6 8]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[2 1 0 ... 4 5 6]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
def init_params():
  W1 = np.random.rand(10,784) - 0.5
  b1 = np.random.rand(10,1) - 0.5
  W2 = np.random.rand(10,10) - 0.5
  b2 = np.random.rand(10,1) - 0.5
  return W1,b1,W2,b2

def ReLU(Z):
  return np.maximum(0,Z)

def softmax(Z):
  return np.exp(Z)/np.sum(np.exp(Z))

def forward(W1, b1, W2, b2, X):
  Z1 = W1.dot(X) + b1
  A1 = ReLU(Z1)
  Z2 = W2.dot(A1) + b2
  A2 = softmax(Z2)
  return Z1, A1, Z2, A2

def one_hot(Y):
  one_hot_Y = np.zeros((Y.size, Y.max() + 1))
  one_hot_Y[np.arange(Y.shape[0]) , Y] = 1
  one_hot_Y = one_hot_Y.T
  return one_hot_Y

def derv_relu(Z):
  return Z>0

def back_prop(Z1, A1, Z2, A2, W2, Y, X):
  m = Y.size
  one_hot_Y = one_hot(Y)
  dZ2 = A2 - one_hot_Y
  dW2 = 1 / m * dZ2.dot(A1.T)
  db2 = 1 / m * np.sum(dZ2)
  dZ1 = W2.T.dot(dZ2) * derv_relu(Z1)
  dW1 = 1 / m * dZ2.dot(X.T)
  db1 = 1 / m * np.sum(dZ1)
  return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
  W1 = W1 - alpha*dW1
  b1 = b1 - alpha*db1
  W2 = W2 - alpha*dW2
  b2 = b2 - alpha*db2
  return W1, b1, W2, b2

In [ ]:
def prediction(A2):
  return np.argmax(A2, 0)

def accuracy(predictions, Y):
  return np.sum(predictions==Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
  W1, b1, W2, b2 = init_params()
  for i in range(iterations):
    Z1, A1, Z2, A2 = forward(W1, b1, W2, b2, X)
    dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, Y, X)
    W1, b1, W2, b2 = update_params(W1,b1, W2, b2, dW1, db1, dW2, db2, alpha)
    if(i % 10 == 0):
      print("Iteration : ", i)
      print("Accuracy : ", accuracy(prediction(A2),Y))
  return W1, b1, W2, b2  

In [ ]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 100, 0.1)